voxpupuli/puppet-logrotate

README.md
manifests/init.pp
spec/classes/init_spec.rb

This PR is to fix issue #11 
It also includes some documentation updates for the `::logrotate` class.

Set default package ensure value to 'installed'

---

manifests/defaults.pp
metadata.json

This merge request adds Gentoo support

Add gentoo support

---

spec/classes/defaults_spec.rb
spec/classes/hourly_spec.rb
spec/classes/init_spec.rb
spec/defines/conf_spec.rb
spec/defines/rule_spec.rb

Fix rubocop checks

---

manifests/conf.pp
templates/etc/logrotate.conf.erb

Adding support for maxsize also in main config

---

CHANGELOG.md
README.md
metadata.json
spec/defines/rule_spec.rb

release 2.0.0

---

manifests/conf.pp
manifests/init.pp
manifests/install.pp
manifests/params.pp
spec/classes/init_spec.rb

Add manage_package parameter

---

manifests/init.pp

Enforce minimal string length on logrotate arguments.

---

.sync.yml
.travis.yml
spec/spec_helper_acceptance.rb

enable acceptance tests centos 6/7 ubuntu 14/16

---

.sync.yml
.travis.yml
manifests/params.pp
metadata.json
spec/classes/defaults_spec.rb

Tests $facts['operatingsystem'] to tell Ubuntu and Debian apart.
On (all) Ubuntu /etc/logrotate.conf from package does contain `su root syslog`
On (all) Debian /etc/logrotate.conf from package does not contain `su`
Fixes #114

add support for Debian

---

.fixtures.yml
.msync.yml
Gemfile
spec/classes/coverage_spec.rb
spec/default_facts.yml
spec/spec_helper.rb

modulesync 2.2.0

---

README.md
manifests/rule.pp
spec/defines/rule_spec.rb

This pr removes leftover occurences of su_owner. This parameter was removed in pr #128 
Fixes #40

Remove occurences of su_owner

---

.github/CONTRIBUTING.md
.msync.yml
Gemfile
manifests/conf.pp
manifests/config.pp
manifests/defaults.pp
manifests/rules.pp
spec/spec_helper.rb

modulesync 2.8.0

---

.github/SECURITY.md
.msync.yml
.rubocop.yml
.travis.yml
Gemfile
manifests/conf.pp
manifests/config.pp
manifests/defaults.pp
manifests/hourly.pp
manifests/init.pp
manifests/install.pp
manifests/rule.pp
manifests/rules.pp
spec/spec_helper_acceptance.rb

modulesync 3.0.0 & puppet-lint updates

---

metadata.json

Drop EoL Puppet 5. Ubuntu 16 and Debian 8 support

---

REFERENCE.md
metadata.json

Drop Eol Debian 9 Support

---

manifests/defaults.pp

Ensure compatabilty with stdlib 9 by replacing stdlib merge function with + operator.
n/a

convert stdlib merge to + operator

---

metadata.json

OracleLinux: Add 8 & 9 support

---

metadata.json

Add AlmaLinux/Rocky 8 & 9 support

---

metadata.json

Add Debian 11 & 12 support

---

metadata.json

This reverts commit 6a9bf0bef3162c122ff4b60cb85595f6f68abaf3.

Revert "Add CentOS 9 support"

---

.github/workflows/ci.yml
.github/workflows/labeler.yml
.github/workflows/release.yml
.msync.yml
.pmtignore
Gemfile
metadata.json

- **modulesync 9.2.0**
- **modulesync 9.3.0**
- **puppet/systemd: allow 8.x**

puppet/systemd: allow 8.x

---

data/Ubuntu/18.04.yaml
manifests/params.pp
metadata.json
spec/classes/init_spec.rb

Drop EoL Ubuntu 18.04 support

---

data/RedHat/10.yaml
metadata.json

Add EL10 support
