metadata.json
Hi,
due to a typo the dependency check of "puppetlabs/stdlib" fails right now.
This PR will fix this by simply replacing the "-" with a "/"
Regards,
Matthias
=> Fixed typo which produces a dependency warning

manifests/conf.pp, manifests/rule.pp
The space between the hash symbol and 'Add' is a Unicode control symbol
(0x000A). It causes Puppet to fail with "Error: Could not retrieve
catalog from remote server: Error 400 on SERVER: invalid byte sequence
in US-ASCII at /etc/puppet/environments/production/modules/logrotate/manifests/rule.pp:1
on node node01.example.com".
Replace that character by a proper space (0x0020).
=> Remove hidden Unicode character (0x000A) from comments

README.md, manifests/rule.pp, templates/etc/logrotate.d/rule.erb
This adds support for the _maxsize_ directive introduced in logrotate version *3.8.1*, which has been released in 2011 (see: https://github.com/logrotate/logrotate/blob/r3-8-1/CHANGES).
relevant section of *man* for logrotate:
__maxsize__ _size_
Log files are rotated when they grow bigger than size bytes even before the additionally specified time interval (daily, weekly, monthly, or yearly).  The related size option is similar except that it is mutually exclusive with the time interval options, and it causes  log  files  to  be  rotated without regard for the last rotation time.  When maxsize is used, both the size and timestamp of a log file are considered.
=> Add support for maxsize directive

Gemfile
Latest version of rake (11.x) requires Ruby 1.9.3 or newer, so it will
not work with Ruby 1.8.7
=> Update Gemfile for Rake/Ruby version dependencies

manifests/defaults.pp, manifests/init.pp, spec/defines/rule_spec.rb
Ability to define a custom rule for btmp and wtmp and prevent logrotate::defaults class from attempting to define the same rule, causing a duplicate resource declaration error.
Had to re-order to put defaults at the end in order to get things to work properly.
Travis-CI tests for Ruby 1.8.7 will fail due to the latest version of Rake requiring Ruby 1.9.3.  This should be fixed with pull request #19
=> Added ability to override default btmp and/or wtmp

Rakefile, manifests/defaults.pp, spec/defines/conf_spec.rb, spec/defines/rule_spec.rb
Instead of adding every newer release of Ubuntu, let's assume the su_group will remain the same, until the next change is necessary.
=> Fixes #34 - Ubuntu Xenial and up support

README.md, manifests/rule.pp, spec/defines/rule_spec.rb, templates/etc/logrotate.d/rule.erb
Added support for dateyesterday to be used within logrotate rules.
Previous done against the original code by another author.
https://github.com/rodjek/puppet-logrotate/pull/53/files
Adapted those changes to the latest version of the module.
=> Added support for dateyesterday within logrotate::rule

manifests/init.pp
This was always a Hash, as you can see in the README.md, String never work. So the next release should be a patch release, not a major one.
----
This Commit is presented to you by Lufthansa
=> wrong datatype for $config, s/String/Hash

manifests/params.pp
The Variable $default_su_group is not there for osfamily Freebsd. Puppet will fail if you have strict variable checking on.
=> Fix "Puppet Unknown variable: 'default_su_group'"

manifests/conf.pp, spec/defines/conf_spec.rb, templates/etc/logrotate.conf.erb
Allows the setting of dateyesterday globally within logrotate.conf rather than in a specific rule like my last pull request.
=> Allowed dateyesterday at the global level

manifests/config.pp, manifests/init.pp, spec/classes/init_spec.rb
Remove unwanted config files from configdir. Has to be enabled using 
`logrotate::purge_configdir: true`
=> Add purge_configdir to purge old configs

README.md, manifests/rule.pp
The su parameter was removed from the classes and templates in favor of su_owner and su_group.
=> Remove obsolete su parameter in documentation

manifests/params.pp, spec/classes/defaults_spec.rb
Hi voxpopuli team,
Default /etc/logrotate.conf on Ubuntu includes a line containing 'su root syslog', but this line is not present in default config produced by this module.
Although $su_group is properly set to 'syslog' in manifests/config.pp, $su_user stays undefined and the condition in templates/etc/logrotate.conf.erb:46 is not met.
This commit makes sure $su_user is set properly on Ubuntu resulting in missing line being present in default config file.
Cheers
Grzegorz
=> Fix missing su line in default logrotate.conf on Ubuntu

manifests/conf.pp, manifests/init.pp, manifests/rule.pp, types/userorgroup.pp
The regex that matches a valid user or group is operating system and
distribution dependent. For instance, for older distributions the
contents of the useradd man page will often give a recommended regex,
rather than a required one.
Remove the UserOrGroup data type and use String instead to account for
horribly named users and groups.
Fixes #88
=> Remove UserOrGroup type, use String

manifests/conf.pp
This PR re-adds the missing ``$maxsize`` option to ``Logrotate::Conf``. This was regressed during a refactor - see https://github.com/voxpupuli/puppet-logrotate/issues/49. 
I have *only* added this line and *not* tested this as I was not able to get set up for testing this (I ran into gem dependency conflicts).
=> Add missing $maxsize option to Logrotate::Conf

manifests/defaults.pp, manifests/init.pp, spec/classes/init_spec.rb
As I'm configuring the rules for btmp and wtmp on my own, the default rulesets conflict with my rules.
With this change you can disable the generation of the default rules like this:
```
class { '::logrotate':
defaultrule_bwtmp => false,
}
```
=> Make the creation of default [bw]tmp-rulesets configurable

README.md
Declaring both `Logrotate::Conf['/etc/logrotate.conf]` and
`Class['logrotate']` will result in errors from Puppet as described
in #116 which is the result of not using the class correctly. Update
readme to add a not warning users not to do this and update the
example for `Class['logrotate']` to indicate that feature parity
with `Logrotate::Conf['/etc/logrotate.conf']` already exists.
Fixes #116
=> (docs) Update readme with warning note and bigger example of defaults

README.md, manifests/cron.pp, manifests/init.pp, spec/defines/cron_spec.rb, templates/etc/cron/logrotate.erb
This PR add a new parameter 'logrotate_args' for managing the startup parameters of logrotate. It is meant to supersede https://github.com/voxpupuli/puppet-logrotate/pull/67 which allows user to manage optional state file with similar technique.
The new parameter takes the arguments as an array. For example:
logrotate::logrotate_args: ['-s /var/lib/logrotate/logrotate.status', '-m /usr/local/bin/mailer'] 
Added new unit tests for the cron.pp
=> Manage logrotate startup arguments

manifests/params.pp
FreeBSD don't have any log file wtmp or btmp. So put logrotate rules by default on this files are useless.
The modification was tested on FreeBSD 11.1 with success.
There is no issue on it.
=> Fix freebsd default rules

README.md, manifests/cron.pp, manifests/init.pp, spec/defines/cron_spec.rb, templates/etc/cron/logrotate.erb
I was used to the fact that redhat always mails its output. I enabled
the managed_cron bool, and added the --verbose startup argument (for
debugging) and all mail went away...
=> Allow cron to always mail its output.

manifests/params.pp
Fixed params for Ubuntu to ensure su is set because su_user and su_group are no longer sufficient to get the logrotate.conf template to output the su directive.
No issue raised.
=> Fixed params for Ubuntu to ensure su is set

manifests/init.pp, manifests/params.pp
The parameter logrotate::cron_hourly_file has already been removed in
favor of using logrotate::cron.
The parameter logrotate::cron_hourly_file has already been removed in
favor of using logrotate::cron.
=> Remove unused parameter: logrotate::cron_hourly_file

README.md
This PR documents that it is possible to use an array of strings describing paths for the `path` rule configuration directive.  Includes an added example.
Also moved the note about cron output to the previous section as it seemed out of place, and fixed an extra closing brace in a prior example.
n/a.
=> Document possible use of Array for paths

manifests/cron.pp, manifests/params.pp, spec/classes/defaults_spec.rb, spec/defines/cron_spec.rb, spec/defines/rule_spec.rb
Replacing `$::osfamily` as running tests against Puppet 6 suggest it no longer exists, and instead only exists in `$facts`
=> Use modern facts and $facts hash for osfamily

manifests/config.pp, spec/classes/init_spec.rb
This PR removes the usage of the deprecated `is_hash` function and moves the creation of `Logrotate::Conf[$logrotate_conf]` to a native Puppet 4 way.
=> Remove deprecated and unused is_hash function

metadata.json
Update the metadata.json file to support using puppetlabs-stdlib v6
Full changelog: https://github.com/puppetlabs/puppetlabs-stdlib/compare/5.2.0...v6.0.0
Short changelog: https://forge.puppet.com/puppetlabs/stdlib/changelog#supported-release-600
The only thing that seems concerning for this module might be https://github.com/puppetlabs/puppetlabs-stdlib/commit/9e8ce942961f9d615203efa4da2de570cf9f420e but defer to you fine folks on that. 
n/a
=> Allow puppetlabs-stdlib 6

manifests/params.pp
Gentoo changed paths and us now using `/usr/bin/logrotate` instead of `/usr/sbin/logrotate`
See https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/logrotate/logrotate-3.14.0.ebuild#n85
This PR fixes the path to the logrotate binary when using Gentoo
Fixes #167
=> Use /usr/sbin/logrotate as $logrotate_bin default value with Gentoo

.sync.yml, .travis.yml, metadata.json
Now that CentOS 6 is EOL and is being removed from the mirror network we have no way to test this anymore.
=> Drop EOL EL6 support

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, .puppet-lint.rc, Dockerfile, Gemfile, Rakefile, spec/acceptance/class_spec.rb, spec/classes/defaults_spec.rb, spec/classes/init_spec.rb, spec/defines/conf_spec.rb, spec/defines/cron_spec.rb, spec/defines/rule_spec.rb, spec/shared_examples.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb
Update to latest modulesync
N/A
=> modulesync 5.3.0

manifests/params.pp, metadata.json, spec/classes/defaults_spec.rb, spec/defines/rule_spec.rb
RHEL8 and later use a slightly different default for `wtmp`
N/A
=> Update defaults to match RHEL8/9

.fixtures.yml, manifests/hourly.pp, metadata.json, spec/classes/init_spec.rb
When EL9 switched to using systemd (quite correctly ) in #216 support for a special directory for hourly logrotations was removed - that change was backwards incompatible.
Add that functionality back with a new unit and timer
* `logrotate-hourly.service`
* `logrotate-hourly.timer`
While this could be achieved by reducing the period of existing timer to hourly I presume the motivation for this was to avoid processing all logrotate directives every hour which does make some sense.
Following this patch:
```
Mon 2024-02-19 14:00:00 CET 46min left  -                           -            logrotate-hourly.timer       logrotate-hourly.service
Tue 2024-02-20 00:00:00 CET 10h left    Mon 2024-02-19 09:53:53 CET 3h 19min ago logrotate.timer              logrotate.service
```
and
```
ExecStart={ …
```
=> Support hourly logrotate directory on EL9 again.

.github/CONTRIBUTING.md, .github/labeler.yml, .github/release.yml, .github/workflows/labeler.yml, .github/workflows/release.yml, .msync.yml, .puppet-lint.rc, .sync.yml, Gemfile, spec/classes/defaults_spec.rb, spec/classes/init_spec.rb, spec/defines/cron_spec.rb, spec/spec_helper.rb
=> modulesync 9.1.0

data/Ubuntu.yaml, data/Ubuntu/18.04.yaml, hiera.yaml, manifests/params.pp, metadata.json, spec/classes/defaults_spec.rb, spec/classes/init_spec.rb
Add Ubuntu 20.04, 22.04, 24.04 support:
- Update default value "su_group" to be in line with Ubuntu 20.04+
- default to systemd-timer instead of cron on Ubuntu 20.04+
Fixes:
- #218
- #191
- #154
Supersedes:
- https://github.com/voxpupuli/puppet-logrotate/pull/231
=> Add Ubuntu 20.04, 22.04, 24.04 support

REFERENCE.md, data/RedHat/9.yaml, data/Ubuntu.yaml, manifests/hourly.pp, manifests/init.pp, spec/classes/init_spec.rb
Similar to the option to disable hourly logrotation when using Cron (`logrotate::ensure_cron_hourly => absent`) this change allows to optionally disable hourly logrotation when using systemd. Previously this was not possible; when the systemd timer/service for logrotate is managed then the hourly logrotation timer/service is also present and enabled.
With this change we introduce the class parameter
`logrotate::ensure_systemd_timer_hourly` which defaults to "present", but can be set to "absent" so that any hourly logrotation timer, service and drop-in are removed.
This can be useful in cases where the usage of "flock" conflicts with "postrotate" commands that inadvertently take ownership of the lock file and keep it open indefinitely; this results in logrotate blocking completely and …
=> Allow disabling logrotate-hourly when using systemd
